In [1]:
import numpy as np

n = np.random.randint(0, 10, 10000)
h = np.bincount(n)
h

array([ 940, 1063, 1016,  978,  964,  964, 1049,  968, 1038, 1020])

In [2]:
h = h/h.sum()
h

array([0.094 , 0.1063, 0.1016, 0.0978, 0.0964, 0.0964, 0.1049, 0.0968,
       0.1038, 0.102 ])

In [6]:
t = np.random.binomial(5, 0.3, size=1000)
s = np.bincount(t)
s

array([172, 370, 306, 128,  24])

In [7]:
s/s.sum()

array([0.172, 0.37 , 0.306, 0.128, 0.024])